"""empty message

Revision ID: 126a74928a89
Revises: c4dc6139fb67
Create Date: 2022-04-22 00:49:56.442875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '126a74928a89'
down_revision = 'c4dc6139fb67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('vendor_push_notification_token', sa.String(length=255), nullable=True))
    op.drop_index('ix_vendors_vendor_push_notofication_token', table_name='vendors')
    op.create_index(op.f('ix_vendors_vendor_push_notification_token'), 'vendors', ['vendor_push_notification_token'], unique=True)
    op.drop_column('vendors', 'vendor_push_notofication_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('vendor_push_notofication_token', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_vendors_vendor_push_notification_token'), table_name='vendors')
    op.create_index('ix_vendors_vendor_push_notofication_token', 'vendors', ['vendor_push_notofication_token'], unique=False)
    op.drop_column('vendors', 'vendor_push_notification_token')
    # ### end Alembic commands ###
