"""empty message

Revision ID: 13130e2f4c4e
Revises: 45912c76a5a6
Create Date: 2022-04-21 01:57:18.321004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13130e2f4c4e'
down_revision = '45912c76a5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('password', sa.String(length=255), nullable=True))
    op.drop_index('ix_customers_customer_password', table_name='customers')
    op.create_index(op.f('ix_customers_password'), 'customers', ['password'], unique=True)
    op.drop_column('customers', 'customer_password')
    op.add_column('vendors', sa.Column('password', sa.String(length=255), nullable=True))
    op.drop_index('ix_vendors_vendor_password', table_name='vendors')
    op.create_index(op.f('ix_vendors_password'), 'vendors', ['password'], unique=True)
    op.drop_column('vendors', 'vendor_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('vendor_password', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_vendors_password'), table_name='vendors')
    op.create_index('ix_vendors_vendor_password', 'vendors', ['vendor_password'], unique=False)
    op.drop_column('vendors', 'password')
    op.add_column('customers', sa.Column('customer_password', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_customers_password'), table_name='customers')
    op.create_index('ix_customers_customer_password', 'customers', ['customer_password'], unique=False)
    op.drop_column('customers', 'password')
    # ### end Alembic commands ###
