"""empty message

Revision ID: 22f20ee18c47
Revises: 46fe328064f0
Create Date: 2022-04-21 23:59:23.639201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22f20ee18c47'
down_revision = '46fe328064f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_admin_name', table_name='admin')
    op.drop_column('admin', 'admin_name')
    op.drop_index('ix_customers_customer_name', table_name='customers')
    op.drop_column('customers', 'customer_name')
    op.drop_index('ix_vendors_vendor_name', table_name='vendors')
    op.drop_column('vendors', 'vendor_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('vendor_name', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('ix_vendors_vendor_name', 'vendors', ['vendor_name'], unique=False)
    op.add_column('customers', sa.Column('customer_name', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('ix_customers_customer_name', 'customers', ['customer_name'], unique=False)
    op.add_column('admin', sa.Column('admin_name', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('ix_admin_admin_name', 'admin', ['admin_name'], unique=False)
    # ### end Alembic commands ###
