"""empty message

Revision ID: 3bdb9ffb489e
Revises: 22f20ee18c47
Create Date: 2022-04-22 00:00:28.626204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bdb9ffb489e'
down_revision = '22f20ee18c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('admin_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_admin_admin_name'), 'admin', ['admin_name'], unique=False)
    op.add_column('customers', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_customers_customer_name'), 'customers', ['customer_name'], unique=False)
    op.add_column('vendors', sa.Column('vendor_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_vendors_vendor_name'), 'vendors', ['vendor_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_vendor_name'), table_name='vendors')
    op.drop_column('vendors', 'vendor_name')
    op.drop_index(op.f('ix_customers_customer_name'), table_name='customers')
    op.drop_column('customers', 'customer_name')
    op.drop_index(op.f('ix_admin_admin_name'), table_name='admin')
    op.drop_column('admin', 'admin_name')
    # ### end Alembic commands ###
