"""empty message

Revision ID: 45912c76a5a6
Revises: 5435266e3929
Create Date: 2022-04-21 01:20:58.090880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45912c76a5a6'
down_revision = '5435266e3929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.String(length=255), nullable=True),
    sa.Column('admin_name', sa.String(length=255), nullable=True),
    sa.Column('admin_email', sa.String(length=255), nullable=True),
    sa.Column('admin_password', sa.String(length=255), nullable=True),
    sa.Column('admin_push_notification_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_admin_email'), 'admin', ['admin_email'], unique=True)
    op.create_index(op.f('ix_admin_admin_id'), 'admin', ['admin_id'], unique=True)
    op.create_index(op.f('ix_admin_admin_name'), 'admin', ['admin_name'], unique=True)
    op.create_index(op.f('ix_admin_admin_password'), 'admin', ['admin_password'], unique=True)
    op.create_index(op.f('ix_admin_admin_push_notification_token'), 'admin', ['admin_push_notification_token'], unique=True)
    op.drop_index('ix_users_admin_email', table_name='users')
    op.drop_index('ix_users_admin_id', table_name='users')
    op.drop_index('ix_users_admin_name', table_name='users')
    op.drop_index('ix_users_admin_password', table_name='users')
    op.drop_index('ix_users_admin_push_notofication_token', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('admin_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('admin_email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('admin_password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('admin_push_notofication_token', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_admin_push_notofication_token', 'users', ['admin_push_notofication_token'], unique=False)
    op.create_index('ix_users_admin_password', 'users', ['admin_password'], unique=False)
    op.create_index('ix_users_admin_name', 'users', ['admin_name'], unique=False)
    op.create_index('ix_users_admin_id', 'users', ['admin_id'], unique=False)
    op.create_index('ix_users_admin_email', 'users', ['admin_email'], unique=False)
    op.drop_index(op.f('ix_admin_admin_push_notification_token'), table_name='admin')
    op.drop_index(op.f('ix_admin_admin_password'), table_name='admin')
    op.drop_index(op.f('ix_admin_admin_name'), table_name='admin')
    op.drop_index(op.f('ix_admin_admin_id'), table_name='admin')
    op.drop_index(op.f('ix_admin_admin_email'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
