"""empty message

Revision ID: 46fe328064f0
Revises: b6fb2df99ea1
Create Date: 2022-04-21 23:25:46.766741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46fe328064f0'
down_revision = 'b6fb2df99ea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apikey_vendor', sa.String(length=255), nullable=True),
    sa.Column('apikey', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apikeys_apikey'), 'apikeys', ['apikey'], unique=True)
    op.create_index(op.f('ix_apikeys_apikey_vendor'), 'apikeys', ['apikey_vendor'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apikeys_apikey_vendor'), table_name='apikeys')
    op.drop_index(op.f('ix_apikeys_apikey'), table_name='apikeys')
    op.drop_table('apikeys')
    # ### end Alembic commands ###
