"""empty message

Revision ID: 480c750ccded
Revises: 8b8551955757
Create Date: 2022-04-23 00:02:34.647686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480c750ccded'
down_revision = '8b8551955757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('permitted', sa.Boolean(), nullable=True))
    op.add_column('customers', sa.Column('permitted_by', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'permitted_by')
    op.drop_column('customers', 'permitted')
    # ### end Alembic commands ###
