"""empty message

Revision ID: 565f53351eec
Revises: 685970c4379e
Create Date: 2022-04-22 10:45:59.855021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '565f53351eec'
down_revision = '685970c4379e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_image_name', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('product_image_filepath', sa.String(length=255), nullable=True))
    op.drop_index('ix_products_product_image', table_name='products')
    op.create_index(op.f('ix_products_product_image_filepath'), 'products', ['product_image_filepath'], unique=True)
    op.create_index(op.f('ix_products_product_image_name'), 'products', ['product_image_name'], unique=True)
    op.drop_column('products', 'product_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_image', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_products_product_image_name'), table_name='products')
    op.drop_index(op.f('ix_products_product_image_filepath'), table_name='products')
    op.create_index('ix_products_product_image', 'products', ['product_image'], unique=False)
    op.drop_column('products', 'product_image_filepath')
    op.drop_column('products', 'product_image_name')
    # ### end Alembic commands ###
