"""empty message

Revision ID: 685970c4379e
Revises: e1ca17feefdf
Create Date: 2022-04-22 02:05:51.067134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685970c4379e'
down_revision = 'e1ca17feefdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_id', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('product_name', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('product_description', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('product_price', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('product_image', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('product_discount', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('product_owner', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('product_is_available', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_products_product_description'), 'products', ['product_description'], unique=False)
    op.create_index(op.f('ix_products_product_discount'), 'products', ['product_discount'], unique=False)
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=True)
    op.create_index(op.f('ix_products_product_image'), 'products', ['product_image'], unique=True)
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.create_index(op.f('ix_products_product_price'), 'products', ['product_price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_product_price'), table_name='products')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_index(op.f('ix_products_product_image'), table_name='products')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_index(op.f('ix_products_product_discount'), table_name='products')
    op.drop_index(op.f('ix_products_product_description'), table_name='products')
    op.drop_column('products', 'product_is_available')
    op.drop_column('products', 'product_owner')
    op.drop_column('products', 'product_discount')
    op.drop_column('products', 'product_image')
    op.drop_column('products', 'product_price')
    op.drop_column('products', 'product_description')
    op.drop_column('products', 'product_name')
    op.drop_column('products', 'product_id')
    # ### end Alembic commands ###
