"""empty message

Revision ID: 8b8551955757
Revises: f74fc82decb5
Create Date: 2022-04-22 22:46:02.617187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8551955757'
down_revision = 'f74fc82decb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_is_featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_is_featured')
    # ### end Alembic commands ###
