"""empty message

Revision ID: 962c9f9e9346
Revises: b450e0138967
Create Date: 2022-05-02 00:41:37.894877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '962c9f9e9346'
down_revision = 'b450e0138967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_order_id', table_name='orders')
    op.drop_index('ix_orders_order_product_description', table_name='orders')
    op.drop_index('ix_orders_order_product_discount', table_name='orders')
    op.drop_index('ix_orders_order_product_id', table_name='orders')
    op.drop_index('ix_orders_order_product_image', table_name='orders')
    op.drop_index('ix_orders_order_product_name', table_name='orders')
    op.drop_index('ix_orders_order_product_price', table_name='orders')
    op.drop_index('ix_orders_order_product_quantity', table_name='orders')
    op.drop_index('ix_orders_order_product_total_price', table_name='orders')
    op.drop_index('ix_orders_order_user_id', table_name='orders')
    op.drop_index('ix_orders_order_vendor_id', table_name='orders')
    op.drop_column('orders', 'order_id')
    op.drop_column('orders', 'order_vendor_id')
    op.drop_column('orders', 'order_product_quantity')
    op.drop_column('orders', 'order_product_description')
    op.drop_column('orders', 'order_product_discount')
    op.drop_column('orders', 'order_product_name')
    op.drop_column('orders', 'order_product_price')
    op.drop_column('orders', 'order_date')
    op.drop_column('orders', 'order_user_id')
    op.drop_column('orders', 'order_product_total_price')
    op.drop_column('orders', 'order_product_image')
    op.drop_column('orders', 'order_product_id')
    op.drop_column('orders', 'order_product_is_available')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_product_is_available', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('order_product_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_product_image', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_product_total_price', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_user_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_date', mysql.DATETIME(), nullable=True))
    op.add_column('orders', sa.Column('order_product_price', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_product_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_product_discount', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_product_description', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_product_quantity', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_vendor_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_id', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('ix_orders_order_vendor_id', 'orders', ['order_vendor_id'], unique=False)
    op.create_index('ix_orders_order_user_id', 'orders', ['order_user_id'], unique=False)
    op.create_index('ix_orders_order_product_total_price', 'orders', ['order_product_total_price'], unique=False)
    op.create_index('ix_orders_order_product_quantity', 'orders', ['order_product_quantity'], unique=False)
    op.create_index('ix_orders_order_product_price', 'orders', ['order_product_price'], unique=False)
    op.create_index('ix_orders_order_product_name', 'orders', ['order_product_name'], unique=False)
    op.create_index('ix_orders_order_product_image', 'orders', ['order_product_image'], unique=False)
    op.create_index('ix_orders_order_product_id', 'orders', ['order_product_id'], unique=False)
    op.create_index('ix_orders_order_product_discount', 'orders', ['order_product_discount'], unique=False)
    op.create_index('ix_orders_order_product_description', 'orders', ['order_product_description'], unique=False)
    op.create_index('ix_orders_order_id', 'orders', ['order_id'], unique=False)
    # ### end Alembic commands ###
