"""empty message

Revision ID: abaa88902f25
Revises: 
Create Date: 2023-02-24 22:59:24.263550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abaa88902f25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.String(length=255), nullable=True),
    sa.Column('admin_name', sa.String(length=255), nullable=True),
    sa.Column('admin_email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('admin_reset_pin', sa.String(length=255), nullable=True),
    sa.Column('admin_push_notification_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_email'),
    sa.UniqueConstraint('admin_id'),
    sa.UniqueConstraint('admin_push_notification_token'),
    sa.UniqueConstraint('admin_reset_pin')
    )
    op.create_table('apikeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apikey_vendor', sa.String(length=255), nullable=True),
    sa.Column('apikey', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apikey'),
    sa.UniqueConstraint('apikey_vendor')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('customer_address', sa.Text(length=2000), nullable=True),
    sa.Column('customer_cards', sa.Text(length=2000), nullable=True),
    sa.Column('customer_reset_pin', sa.String(length=255), nullable=True),
    sa.Column('customer_push_notification_token', sa.String(length=255), nullable=True),
    sa.Column('permitted', sa.Boolean(), nullable=True),
    sa.Column('permitted_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_email'),
    sa.UniqueConstraint('customer_id'),
    sa.UniqueConstraint('customer_push_notification_token'),
    sa.UniqueConstraint('customer_reset_pin'),
    sa.UniqueConstraint('password')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('order_vendor_id', sa.String(length=255), nullable=True),
    sa.Column('order_customer_id', sa.String(length=255), nullable=True),
    sa.Column('order_product_id', sa.String(length=255), nullable=True),
    sa.Column('item_unique_id', sa.String(length=255), nullable=True),
    sa.Column('order_product_name', sa.String(length=255), nullable=True),
    sa.Column('order_product_price', sa.String(length=255), nullable=True),
    sa.Column('order_product_discount', sa.String(length=255), nullable=True),
    sa.Column('order_product_quantity', sa.String(length=255), nullable=True),
    sa.Column('order_total_price', sa.String(length=255), nullable=True),
    sa.Column('order_product_image', sa.String(length=255), nullable=True),
    sa.Column('order_product_description', sa.String(length=255), nullable=True),
    sa.Column('order_product_is_available', sa.Boolean(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_unique_id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_description', sa.String(length=255), nullable=True),
    sa.Column('product_price', sa.String(length=255), nullable=True),
    sa.Column('product_image_name', sa.String(length=255), nullable=True),
    sa.Column('product_image_filepath', sa.String(length=255), nullable=True),
    sa.Column('product_discount', sa.Integer(), nullable=True),
    sa.Column('product_owner', sa.String(length=255), nullable=True),
    sa.Column('product_is_available', sa.Boolean(), nullable=True),
    sa.Column('product_is_featured', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id'),
    sa.UniqueConstraint('product_image_filepath'),
    sa.UniqueConstraint('product_image_name')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(length=255), nullable=True),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('vendor_email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('vendor_reset_pin', sa.String(length=255), nullable=True),
    sa.Column('permitted', sa.Boolean(), nullable=True),
    sa.Column('permitted_by', sa.String(length=255), nullable=True),
    sa.Column('vendor_push_notification_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('vendor_email'),
    sa.UniqueConstraint('vendor_id'),
    sa.UniqueConstraint('vendor_push_notification_token'),
    sa.UniqueConstraint('vendor_reset_pin')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendors')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('customers')
    op.drop_table('apikeys')
    op.drop_table('admin')
    # ### end Alembic commands ###
