"""empty message

Revision ID: b6fb2df99ea1
Revises: 13130e2f4c4e
Create Date: 2022-04-21 02:12:55.069334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6fb2df99ea1'
down_revision = '13130e2f4c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password', sa.String(length=255), nullable=True))
    op.drop_index('ix_admin_admin_password', table_name='admin')
    op.create_index(op.f('ix_admin_password'), 'admin', ['password'], unique=True)
    op.drop_column('admin', 'admin_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('admin_password', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_admin_password'), table_name='admin')
    op.create_index('ix_admin_admin_password', 'admin', ['admin_password'], unique=False)
    op.drop_column('admin', 'password')
    # ### end Alembic commands ###
