"""empty message

Revision ID: c4dc6139fb67
Revises: 3bdb9ffb489e
Create Date: 2022-04-22 00:30:57.995464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4dc6139fb67'
down_revision = '3bdb9ffb489e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('customer_push_notification_token', sa.String(length=255), nullable=True))
    op.drop_index('ix_customers_customer_push_notofication_token', table_name='customers')
    op.create_index(op.f('ix_customers_customer_push_notification_token'), 'customers', ['customer_push_notification_token'], unique=True)
    op.drop_column('customers', 'customer_push_notofication_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('customer_push_notofication_token', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_customers_customer_push_notification_token'), table_name='customers')
    op.create_index('ix_customers_customer_push_notofication_token', 'customers', ['customer_push_notofication_token'], unique=False)
    op.drop_column('customers', 'customer_push_notification_token')
    # ### end Alembic commands ###
