"""empty message

Revision ID: e1ca17feefdf
Revises: 126a74928a89
Create Date: 2022-04-22 02:05:35.023004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1ca17feefdf'
down_revision = '126a74928a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_product_description', table_name='products')
    op.drop_index('ix_products_product_discount', table_name='products')
    op.drop_index('ix_products_product_id', table_name='products')
    op.drop_index('ix_products_product_image', table_name='products')
    op.drop_index('ix_products_product_name', table_name='products')
    op.drop_index('ix_products_product_price', table_name='products')
    op.drop_column('products', 'product_is_available')
    op.drop_column('products', 'product_discount')
    op.drop_column('products', 'product_description')
    op.drop_column('products', 'product_price')
    op.drop_column('products', 'product_image')
    op.drop_column('products', 'product_id')
    op.drop_column('products', 'product_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('products', sa.Column('product_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('products', sa.Column('product_image', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('products', sa.Column('product_price', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('products', sa.Column('product_description', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('products', sa.Column('product_discount', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('product_is_available', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_index('ix_products_product_price', 'products', ['product_price'], unique=False)
    op.create_index('ix_products_product_name', 'products', ['product_name'], unique=False)
    op.create_index('ix_products_product_image', 'products', ['product_image'], unique=False)
    op.create_index('ix_products_product_id', 'products', ['product_id'], unique=False)
    op.create_index('ix_products_product_discount', 'products', ['product_discount'], unique=False)
    op.create_index('ix_products_product_description', 'products', ['product_description'], unique=False)
    # ### end Alembic commands ###
